[package]
name = "rag_with_rust"
version = "0.1.0"
edition = "2021"


[dependencies]
futures = "0.3.31"
langchain-rust = { version = "4.6.0", features = ["ollama", "qdrant"] }
pkg-config = "0.3.31"
serde_json = "1.0.138"
tokio = "1.38.1"
tokio-stream = "0.1.17"

