[package]
name = "rag_with_rust"
version = "0.1.0"
edition = "2021"


[dependencies]
futures-util = "0.3.30"
langchain-rust = { version = "4.3.0", features = ["ollama", "ollama-rs"] }
serde_json = "1.0.120"
tokio = "1.38.0"
